apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: workflows
spec:
  containers:
    - image: google/cloud-sdk:slim
      name: workload-identity-test
      command: ["sleep","infinity"]
  serviceAccountName: argo-terraform
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"