---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform
  namespace: argo
spec:
  templates:
    - name: plan
      inputs:
        artifacts:
          - name: terraform
            path: /home/terraform
            git:
              repo: https://github.com/tony-mw/argo-demo.git
              depth: 1
      script:
        imagePullPolicy: "Always"
        image: hashicorp/terraform:latest
        command: ["sh"]
        source: |
          terraform init -input=false /home/terraform
          terraform plan -parallelism=2 -input=false -no-color -out=/home/terraform/tfclientsplan /home/terraform >> /tmp/terraform-change.log
      outputs:
        artifacts:
          - name: terraform-plan
            path: /home/myuser/
            archive:
              none: {}
          - name: terraform-log
            path: /tmp/terraform-change.log
            archive:
              none: {}

    - name: apply
      inputs:
        artifacts:
          - name: terraform-plan
            path: /home/terraform
      serviceAccountName: argo
      script:
        imagePullPolicy: "Always"
        image: hashicorp/terraform:latest
        command: ["sh"]
        source: |
          terraform apply -input=false -parallelism=2 -no-color /home/terraform/tfclientsplan

    - name: approve
      suspend: {}

    - name: update
      dag:
        tasks:
          - name: plan
            template: plan
            outputs:
              artifacts:
                - name: terraform-plan
                  path: /home/myuser/
          - name: approve
            dependencies: [plan]
            template: approve
          - name: apply
            template: apply
            dependencies: [plan, approve]
            arguments:
              artifacts:
                - name: terraform-plan
                  from: "{{tasks.plan.outputs.artifacts.terraform-plan}}"