apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: Deploy the terraform
    workflows.argoproj.io/maintainer: 'good_people'
    workflows.argoproj.io/tags: terraform
    workflows.argoproj.io/version: '>= 2.9.0'
  name: terraform-basic
spec:
  serviceAccountName: argo-terraform
  entrypoint: update
  arguments:
    parameters:
      - name: terraform-docker-image
        value: "apresti12/argo-terraform:latest"
      - name: terraform-script-repository
        value: "https://github.com/tony-mw/argo-demo.git"
  templates:
    - name: plan
      inputs:
        artifacts:
          - name: terraform
            path: /home/argo
            git:
              repo: "{{workflow.parameters.terraform-script-repository}}"
              depth: 1
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: |
          pwd
          whoami
          ls -la
          terraform -chdir=/home/argo/terraform/dev init -input=false
          echo "Init Complete"
          terraform -chdir=/home/argo/terraform/dev plan -parallelism=2 -input=false -no-color -out=/home/argo/tfclientsplan >> /home/argo/terraform-change.log
          echo "Plan Complete"
          ls -la terraform/dev
      outputs:
        artifacts:
          - name: terraform-plan
            path: /home/argo/
            gcs:
              bucket: mw-argo-workflows-artifacts
              key: terraform/plan
            archive:
              none: {}
          - name: terraform-log
            path: /home/argo/terraform-change.log
            gcs:
              bucket: mw-argo-workflows-artifacts
              key: terraform/log
            archive:
              none: {}

    - name: apply
      inputs:
        artifacts:
          - name: terraform-plan
            path: /home/argo
      script:
        imagePullPolicy: "Always"
        image: "{{workflow.parameters.terraform-docker-image}}"
        command: ["sh"]
        source: |
          pwd
          whoami
          ls -la
          terraform -chdir=/home/argo/terraform/dev init -input=false
          chmod 755 -R /home/argo/terraform/dev/.terraform
          terraform -chdir=/home/argo/terraform/dev apply -input=false -parallelism=2 -no-color /home/argo/tfclientsplan

    - name: approve
      suspend: {}

    - name: update
      dag:
        tasks:
          - name: plan
            template: plan
          - name: approve
            dependencies: [plan]
            template: approve
          - name: apply
            template: apply
            dependencies: [plan, approve]
            arguments:
              artifacts:
                - name: terraform-plan
                  from: "{{tasks.plan.outputs.artifacts.terraform-plan}}"

