apiVersion: v1
data:
  token: "Z2hwXzdDMFBZdG43dmh1ZG5jcksxWXpEUWJRcWRLN05uazQwdHRCRgo="
kind: Secret
metadata:
  name: github-access
  namespace: workflows
  resourceVersion: "27984"
  uid: daea7701-e698-4e2c-ac06-4bee7dc1d5fc
type: Opaque
